version: '3.8'
services:

  frontend:
    image: valentindevpy/foodgram-front:latest
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  web:
    image: valentindevpy/foodgram:latest
    platform: linux/x86_64
    restart: always
    volumes:
      - ../backend/src:/app
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    restart: always
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/django_static/
      - media_value:/var/html/django_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
volumes:
  static_value:
  media_value:
