# Generated by Django 4.0.6 on 2022-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscribe",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "subscribed_for"), name="unique subscribe object"
            ),
        ),
    ]
