# Generated by Django 4.0.6 on 2022-08-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribe_unique subscribe object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
